# Generated by Django 3.2.25 on 2024-12-18 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('City', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='emoji',
        ),
    ]
