# Generated by Django 5.1.1 on 2024-10-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('City', '0002_city_delete_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='city',
            name='lng',
        ),
        migrations.AddField(
            model_name='city',
            name='position',
            field=models.JSONField(default=''),
        ),
    ]
