# Generated by Django 3.2.25 on 2024-12-18 21:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('City', '0002_remove_city_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
