# Generated by Django 5.1.1 on 2024-10-09 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('City', '0003_remove_city_lat_remove_city_lng_city_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='position',
        ),
        migrations.AddField(
            model_name='city',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='city',
            name='lng',
            field=models.FloatField(default=0.0),
        ),
    ]
