# Generated by Django 5.1.1 on 2024-10-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/dueoghvvo/image/upload/v1724810506/default_profile_kstxax.jpg', upload_to='images/'),
        ),
    ]
