# Generated by Django 5.1.1 on 2024-10-04 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_profile_image_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image_filter',
        ),
    ]
