# Generated by Django 5.1.1 on 2024-10-04 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0008_remove_profile_image_filter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='username',
        ),
    ]
