# Generated by Django 5.1.1 on 2024-10-09 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0010_remove_profile_user_customuser_delete_note_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
